### ISSUE TITLE
Print block type rejection

### ISSUE THREAD

**Issue by dube1503** [txst-per-group/Glowscript-Blocks#111]
Currently the print block accepts multiple variable type inputs and running the program with some of these types connected causes unusual and hard to diagnose error problems.
The print block should only except 'Number' 'Vector' 'Boolean' and 'String' type inputs _currently_ to avoid problem programs

**Comment by codestar12** [comment]
@dube1503 I think booleans should also be included in the accepted inputs. You are allowed to print the value of a boolean variable in glowscript and python
