### ISSUE TITLE
Repo rename

### ISSUE THREAD

**Issue by eah13** [txst-per-group/Glowscript-Blocks#2]
As we discussed, it might be good to rename this repo `glowscript-blocks`, sooner rather than later.  We'll need to coordinate changing the dev server setup and of course update the `git remote` urls for any cloned repos.  The earlier the better so this URL doesn't get hardcoded in lots of places.

**Comment by eah13** [comment]
@codestar12 also, if you add me as a collaborator to this repo that will let me make tags and tag issues.

**Comment by brianpmarks** [comment]
Just a quick heads up - our [development environment](http://glowscript-blocks-dev.trinket.io/embed/glowscript-blocks) may be briefly unavailable as we need to update the name of this repo in our codebase.

**Comment by dube1503** [comment]
@eah13 @brianpmarks I have updated the name which I am sure means the ```git remote``` urls need to update as well as other references. Let us know if we need to make any other updates or releases before we start making other Pull Requests

**Comment by dube1503** [comment]
I adjusted my local clone with ```git remote set-url origin https://github.com/txst-per-group/Glowscript-Blocks.git``` to avoid any confusion on my future merges and pull requests

**Comment by brianpmarks** [comment]
Great! I've updated our development environment to use the new name.
