### ISSUE TITLE
convert math operator generators from python to glowscript syntax

### ISSUE THREAD

**Issue by codestar12** [txst-per-group/Glowscript-Blocks#35]
confirm the following glowscript operators exist and that they output correctly instead of using python (math.pi) output

 
@hgclose  you might want to edit out some of these you don't think will be necessary 

- [x] abs(x)
- [x] sqrt(x)
- [x] sin(x)
- [x] cos(x)
- [x] tan(x)
- [x] asin(x)    # arc sine
- [x] acos(x)    # arc cosine
- [x] atan(x)    # arc tangent
- [x] exp(x)     # e to the x
- [x] log(x)     # natural log, base e
- [x] # log(x)/log(10) gives log base 10
- [x] pi         # 3.14159.... 
- [x] ceil(x)    # round up to nearest integer
- [x] floor(x)   # round down to nearest integer
- [x] round(x)   # round to nearest integer 
- [x] random()   # pseudorandom number 0 to 1
- [x] factorial(x)  # x! = x*(x-1)*(x-2)....(1)

**Comment by hgclose** [comment]
I checked the ones I think we should include

**Comment by codestar12** [comment]
I think I'm going to remove pow(x,y) and atan2 from this list. both can easily be computed useing other existing blocks and would either require their own unique math blocks or require a shared "math double block" which could be confusing

**Comment by hgclose** [comment]
Your reasoning makes sense. I was not in favor including pow(x, y) originally, but I think I had included atan2. I've only used it occasionally, and I agree we can do without it.

**Comment by codestar12** [comment]
I'm going to make a separate issue for min and max as they are turning out to be more complicated than expected and preventing the closing of the rest of the shapes.
