### ISSUE TITLE
modify shape mutators to be more user friendly

### ISSUE THREAD

**Issue by codestar12** [txst-per-group/Glowscript-Blocks#43]
Based on discussion 8/7:

* Reduce space in between unused attribute lists (90% or so if possible) to make them take up less vertical space
* remove blocks from left once selected, if possible, to reduce size of list as attributes are used
* If possible, avoid need for scrollbars

Previous discussion follows.
____

currently the mutators for shape constructor blocks are hard to use because of the large number of possible attributes 

possible solutions

- removing attribute blocks from left hand list when they have been added 
- enabling scroll bar
- converting mutator to a checkbox list of attributes

**Comment by eah13** [comment]
"Friendly attributes" might belong on this scope: things like color, position, size etc that help users discover what properties are modifiable.
