### ISSUE TITLE
Remaining variables issues

### ISSUE THREAD

**Issue by codestar12** [txst-per-group/Glowscript-Blocks#6]
- [x] moving variable blocks above variable defs can cause program to lock
- [X] change wording for selecting vector components from `all` to `vector` in dropdown

**Comment by eah13** [comment]
This one wasn't on the board so may have gotten overlooked.  I set it as a todo there.  We can add repro steps when we groom.

**Comment by codestar12** [comment]
This bug occurred because of how the onChange  function was written and called. On a previous pull request I disabled onChange as it was making coding and test every other bug frustrating. It may be more appropriate to make a task or story to build a comprehensive real time type update system. We can talk more about it Monday

**Comment by dube1503** [comment]
@hgclose the newest bullet is in reference to the discussion we had previously about changing confusing language when referring to vectors and there components in the "get" and "set" variable blocks from just `all` to `vector`. Do you still agree with this solution?

**Comment by hgclose** [comment]
yes, I agree

**Comment by codestar12** [comment]
@hgclose during the process of programming get and set blocks with no defaults it became apparent that writing a block that was disabled until you made a selection was going to be about the same difficult as making a block that automatically detects its assigned type and updates. @eah13 I have a feature branch that I was going to finish the auto type updating set block on, but it closes the original issues of this task and I don't think any of the bugs left are program breaking. I'm not sure what our process dictates we should do with the 'issue', but I think what is left to do is try and build programs and find logical inconsistencies with how we think they should behave and fix them. We can talk more about it today
