### ISSUE TITLE
make_trail = true throwing an error

### ISSUE THREAD

**Issue by brianpmarks** [txst-per-group/Glowscript-Blocks#64]
Simple reproduction steps:

* add a sphere block to the workspace from Shapes
* use the gear icon to add the make_trail block to the sphere
* run the program

Result: error message "true is a reserved word:"

Expected: program to run without error

I suspect true needs to be capitalized.

Here's a link to a trinket in the environment showing the error:

http://glowscript-blocks-dev.trinket.io/embed/glowscript-blocks/0b77535583?start=result

**Comment by dube1503** [comment]
You were correct with the value not being output with capital letters being the issue. Thanks for the suggestion and the code snippet link, was super helpful.
