### ISSUE TITLE
Code Highlighting

### ISSUE THREAD

**Issue by dube1503** [txst-per-group/Glowscript-Blocks#77]
In order for the user to have more relation to the coding/programing aspect of the blocks and to help the user troubleshoot problems in the block stack creation in respect to the code, the generated code should highlight in conjunction with the selected blocks within the workspace.

**Comment by eah13** [comment]
Looks like #79 fixed this one, or at least gives it the current highlighting functionality that Trinket's blocks have.

![screenshot 2017-08-07 at 9 48 28 am](https://user-images.githubusercontent.com/1702745/29029470-bfb5481a-7b55-11e7-9ea9-1d10a36a0e6d.png)

Ready to close IMO.

**Comment by dube1503** [comment]
I believe #79 did resolve this issue. It was just never linked with tags but i think we can go ahead and close this one.
